<a href="https://colab.research.google.com/github/Rahulbhowmik-cpt/DMDW-assignment/blob/main/assigment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment - 2
Execute and explain 10 most used commands in numpy
and 5 most used commands in Pandas

10 commands of numpy

1.Array

In [2]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


2.empty()

In [3]:
import numpy as np
arr=np.empty([2,2])
print(arr)

[[1. 1.]
 [1. 0.]]


3.zeros()

In [6]:
import numpy as np
arr=np.zeros(2,dtype=int)
print(arr)

[0 0]


4.ones()

In [7]:
import numpy as np
arr=np.ones([2,2],dtype=int)
print(arr)

[[1 1]
 [1 1]]


5.vstack

In [8]:
x=np.array([3,5,7])
y=np.array([5,7,9])
print(np.vstack((x,y)))

[[3 5 7]
 [5 7 9]]


6.hstack

In [9]:
x=np.array([3,5,7])
y=np.array([5,7,9])
print(np.hstack((x,y)))

[3 5 7 5 7 9]


7.Indexing 

In [12]:
a=np.array([1,2,3,6,9])
print(a[3])

6


8.Slicing

In [13]:
a=np.array([1,2,3,6,9])
print(a[1:3])

[2 3]


9.shape

In [16]:
x = np.array([ [67, 63, 87],
               [77, 69, 59],
               [85, 87, 99],
               [79, 72, 71],
               [63, 89, 93],
               [68, 92, 78]])

print(np.shape(x))

(6, 3)


10.Reshape

In [21]:
x = np.array([1,2,3,4,5,6,7,8])
new=x.reshape(2,4)
print(new)

[[1 2 3 4]
 [5 6 7 8]]


5 commands of pandas

1.dataframe()

In [27]:
import pandas as pd
lst = [1,2,3]
df = pd.DataFrame(lst)
print(df)

   0
0  1
1  2
2  3


2.head

In [31]:
import pandas as pd
i = pd.DataFrame({1,4,2,4,6})
i.head()
print(i.head(2))

   0
0  1
1  2


3.describe

In [32]:
import pandas as pd
i = pd.Series([1,4,2,4,6])
i.describe()


count    5.000000
mean     3.400000
std      1.949359
min      1.000000
25%      2.000000
50%      4.000000
75%      4.000000
max      6.000000
dtype: float64

4.loc,iloc

In [35]:
import pandas as pd
df = pd.DataFrame({'Weight':[45, 88, 56, 15, 71],
                   'Name':['RAM', 'SITA', 'HANUMAN', 'LAXMAN', 'RAVAN'],
                   'Age':[14, 25, 55, 8, 21]})
index_ = ['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5']
df.index = index_
result = df.loc['Row_2', 'Name']
print(result)
result1=df.iloc[0]
print(result1)



SITA
Weight     45
Name      RAM
Age        14
Name: Row_1, dtype: object
